In [50]:
import numpy as np
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
from tensorflow.keras.preprocessing import text_dataset_from_directory

In [51]:
training_data = np.array([["This is the 1st sample."], ["And here's the 2nd sample ."]])
vectorizer = TextVectorization(output_mode="binary")

In [52]:
vectorizer.adapt(training_data)

In [53]:
print(vectorizer(training_data))

tf.Tensor(
[[0. 1. 1. 1. 1. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0. 1. 1. 1. 0.]], shape=(2, 9), dtype=float32)


In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [69]:
from tensorflow.python.keras.layers import Layer
from tensorflow.keras.layers.experimental.preprocessing import PreprocessingLayer
import numpy as np

class TextPreprocessingLayer(PreprocessingLayer):
    """
    
    """
    
    def __init__(self, **kwargs):
        super(TextPreprocessingLayer, self).__init__(dtype=np.float, **kwargs)
        
    def build(self, input_shape):
        super(TextPreprocessingLayer, self).build(input_shape)
        
    def call(self, inputs, verbose=False):
        print(inputs)
        return 42  

In [67]:
model = keras.Sequential(
    [
        TextVectorization(output_mode="binary", max_tokens=5)
    ])

model.compile(optimizer=keras.optimizers.RMSprop(learning_rate=1e-3),
              loss=keras.losses.CategoricalCrossentropy())

data = np.array([["Hallo"], ["Freunde, das hier ist ein Hallo"]])

In [68]:
model(data)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]], dtype=float32)>

In [49]:
model.summary()

Model: "sequential_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
process (TextPreprocessingLa multiple                  0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [2]:
# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3"),
    ]
)
# Call model on a test input
x = tf.ones((3, 3))
y = model(x)

In [3]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.12771338,  0.17154977,  0.24414457, -0.11119182],
       [ 0.12771338,  0.17154977,  0.24414457, -0.11119182],
       [ 0.12771338,  0.17154977,  0.24414457, -0.11119182]],
      dtype=float32)>

In [14]:
model = keras.Sequential(
    [
        layers.Dense(3, activation="relu", name="layer1")
    ])

In [70]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline

AttributeError: module 'numpy.linalg.lapack_lite' has no attribute '_ilp64'

In [71]:
!pip install sklearn

  Using cached sklearn-0.0.tar.gz (1.1 kB)
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1316 sha256=f35dd7b417b0d1d62e1bdbf6a2735d7850eee59e4ca4c62d40a1aef0f1bae17e
  Stored in directory: /Users/michaelwellner/Library/Caches/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn


In [73]:
!pip install numpy